# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'im' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for im

  # 第一步：添加pod库
  # 集成萝卜丝核心协议库core
  pod 'bytedesk-core'
  # 集成萝卜丝UI库
  pod 'bytedesk-ui'

  target 'imTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
