# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
workspace 'xiaper'

target 'xiaper-tutorial' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for xiaper-tutorial
  pod 'bytedesk-ui'
  pod 'bytedesk-core'

  target 'xiaper-tutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

end